### ISSUE TITLE
エラーが消えないです

### ISSUE THREAD

**Issue by akriaha** [5000trillion/triclo#27]
CodePickActivity.java で (R.id.～～) 全ての R がエラーです。
原因となるxmlは strings_codepick.xml でした。
http://develop.logical-studio.com/development/android_app_beginner/20161003-optionmenu/
を参考に作ったものです。また、xml内でエラーはありません。

**Comment by ookkoouu** [comment]
何度かビルドしてみて

**Comment by multiverse2011** [comment]
わかりません！！！
