### ISSUE TITLE
mainactivity開けない

### ISSUE THREAD

**Issue by ookkoouu** [5000trillion/triclo#38]
130行目でエラーでて落ちている模様

`Caused by: java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/images/media from pid=4033, uid=10078 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()`

**Comment by Ishihara1222** [comment]
みてみます

**Comment by multiverse2011** [comment]
@Ishihara1222 どうなりました？

**Comment by Ishihara1222** [comment]
原因はわかったんですが直せてないです。

**Comment by multiverse2011** [comment]
わかってるようであれば詳細をこのissueに書いておいてください

**Comment by multiverse2011** [comment]
たぶんmediaproviderから受け取れてないよ的なやつなので受け取れなかったときの処理的なことを書いておくといいと思います

**Comment by multiverse2011** [comment]
というかこのエラー、先行して立ててたissue #30 と根は同じです

**Comment by Ishihara1222** [comment]
managedQueryに線が引かれて消されてるのが原因かと思ったんですが

**Comment by multiverse2011** [comment]
ちがいます　あくまでも非推奨って言う意味です

**Comment by Ishihara1222** [comment]
そうなんですか

**Comment by Ishihara1222** [comment]
すいません。どうしても直せないです。

**Comment by ookkoouu** [comment]
とりあえず直しました
ただ画像のサイズがやたら小さくなります
![default](https://user-images.githubusercontent.com/29059223/29650966-20824ed2-88d9-11e7-8ce0-0cd68751cbd4.png)
