### ISSUE TITLE
test

### ISSUE THREAD

**Issue by KenFujita** [5000trillion/triclo#9]
test issues

**Comment by multiverse2011** [comment]
あああ

**Comment by multiverse2011** [comment]
ここでエラーが出ます

`//Logボタンをおした時
    public void showLog(View v){
        //検索用のクエリ作成
        RealmQuery<TestDB> query = realm.where(TestDB.class);

//        query.equalTo("name", "test");
//        query.or().equalTo("id", 2);
//        query.or().equalTo("id", 3);

        //インスタンス生成し、その中にすべてのデータを入れる 今回なら全てのデータ
        RealmResults<TestDB> results = query.findAll();

        //すべての値をログに出力
        for (TestDB test:results){
            System.out.println(test.getName());
        }
    }`

**Comment by multiverse2011** [comment]
@Ishihara1222 はやくやれ
